version: '3.8'

services:
  task_manager:
    build: .
    ports:
      - "8080:8080"  # Expose port 8080 for the task manager
    environment:
      - DB_NAME= ${DB_NAME}
      - DB_HOST= db
      - DB_USER= ${DB_USER}
      - DB_PASSWORD= ${DB_PASSWORD}
      - JWT_SECRET= ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy  # Wait for database readiness

  db:
    image: postgres:latest            
    environment:
      POSTGRES_USER: ${DB_USER}     
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"